apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: opscore-api
      app.kubernetes.io/instance: {{ .Release.Name }}
