apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: opscore-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: opscore-api
    app.kubernetes.io/instance: {{ .Release.Name }}
